global:
  scrape_interval: 10s                          # 10초 마다 Metric 수집. Default Value = 1분
  evaluation_interval: 10s                      # 10초마다 Metric 수집. Default Value = 1분
  # 'scrape_timeout'은 기본적으로 10초로 설정 되어 있음.

# Alertmanager 설정
alerting:
  alertmanagers:
    - static_configs:
        - targets:
          # - alertmanager:9093

# 규칙을 처음 한번 Loading하고, 'evaluation_interval' 설정에 따라 정기적으로 규칙 평가
rule_files:
# - "first_rules.yml"
# - "second_rules.yml"

# Metric 수집 Endpoing 설정.
scrape_configs:
  - job_name: 'giggal-people_spring-monitoring'
    metrics_path: '/actuator/prometheus'
    static_configs:
      #- targets: ['host.docker.internal:9999']
      - targets: ['192.168.100.10:9999']